// @prefab-sync-start - auto generated by sync-prefab-layout.js
// layout from prefab/UISocialInviteView.lh
// nodes resolved by sync-prefab-layout.js
// openData viewport: list@16,0 (prefab list.y=91 为全屏坐标，开放域不重复偏移)
// list: UISocialInviteView/list_items
// item: UISocialInviteView/list_items/item

module.exports = function createStyle(options) {
    options = options || {};

    const canvasWidth = Number(options.canvasWidth) > 0 ? Number(options.canvasWidth) : 720;
    const canvasHeight = Number(options.canvasHeight) > 0 ? Number(options.canvasHeight) : 1280;

    // 根布局尺寸使用实际 sharedCanvas 尺寸
    // 因为 engine 源码里 root/style.width height 决定 renderport
    // 而 sharedCanvas 不能动态改时，root 也不适合盲目大于 canvas 实际尺寸
    const rootWidth = canvasWidth;
    const rootHeight = canvasHeight;
    const listHeight = rootHeight ;

    console.error(Number(options.canvasHeight),listHeight)

    return {
        container: {
            width: rootWidth,
            height: rootHeight,
            flexDirection: "column",
        },
        list: {
            width: 696,
            height: listHeight,
            marginLeft: 16,
            marginTop: 0,
            scrollY: true,
            flexDirection: "column",
        },
        emptyText: {
            width: 696,
            height: 1047,
            marginLeft: 16,
            marginTop: 91,
            fontSize: 24,
            color: "#999999",
            textAlign: "center",
            lineHeight: 1047,
        },
        item: {
            width: 688,
            height: 185,
            position: "relative",
        },
        itemBg: {
            position: "absolute",
            left: 0,
            top: 28,
            width: 688,
            height: 172,
        },
        itemRow: {
            width: 688,
            height: 200,
            flexDirection: "row",
            alignItems: "center",
            paddingLeft: 38,
            paddingRight: 26,
            paddingTop: 64,
            paddingBottom: 21,
        },
        itemHead: {
            width: 100,
            height: 100,
            borderRadius: 50,
        },
        itemNick: {
            fontSize: 32,
            color: "#8a5839",
            verticalAlign: "middle",
            width: 270,
            height: 37,
            textStrokeColor: "#373899",
            textStrokeWidth: 1,
            marginLeft: 24,
        },
        itemBtnWrap: {
            width: 161,
            height: 64,
            marginLeft: 69.5,
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
        },
        itemBtn: {
            width: 161,
            height: 64,
        },
        itemBtnText: {
            fontSize: 32,
            color: "#f8fde4",
            verticalAlign: "middle",
            width: 161,
            height: 64,
            textAlign: "center",
            textStrokeWidth: 4,
            textStrokeColor: "#4d7b26",
            marginTop: -64,
            lineHeight: 64,
        },
    };
};
// @prefab-sync-end