// @prefab-sync-start - auto generated by sync-prefab-layout.js
// layout from prefab/UISocialInviteView.lh
// nodes resolved by sync-prefab-layout.js
// list: UISocialInviteView/list_items
// item: UISocialInviteView/list_items/item

module.exports = function createStyle(options) {
  options = options || {};

  const viewPort = options.viewPort || null;
  const canvasHeight = Number(options.canvasHeight) > 0 ? Number(options.canvasHeight) : 1280;

  // 逻辑坐标宽度固定，保证 item 内部布局不变
  const rootWidth = 720;

  // 根布局高度必须跟 sharedCanvas.height 走
  // 不能直接用 viewport.height，否则会把 Y 轴缩放吃掉
  const rootHeight = canvasHeight;

  // 列表逻辑高度也跟随 sharedCanvas 逻辑高度
  const listHeight = rootHeight;

  const style = {
    container: {
      width: rootWidth,
      height: rootHeight,
      flexDirection: "column",

      // 调试时可打开
      backgroundColor: "rgba(255,0,0,0.15)",
    },

    list: {
      width: 688,
      height: listHeight,
      marginLeft: 12,
      marginTop: 0,
      scrollY: true,
      flexDirection: "column",

      // 调试时可打开
      backgroundColor: "rgba(0,255,0,0.15)",
    },

    emptyText: {
      width: 688,
      height: listHeight,
      marginLeft: 12,
      marginTop: 0,
      fontSize: 24,
      color: "#999999",
      textAlign: "center",
      lineHeight: listHeight,
    },
    item: {
      width: 688,
      height: 185,
      position: "relative",
      marginLeft: 4,
    },
    itemBg: {
      position: "absolute",
      left: 0,
      top: 12,
      width: 688,
      height: 172,
    },
    itemRow: {
      width: 688,
      height: 185,
      flexDirection: "row",
      alignItems: "center",
      paddingLeft: 38,
      paddingRight: 26,
      paddingTop: 48,
      paddingBottom: 37,
    },
    itemHead: {
      width: 100,
      height: 100,
      borderRadius: 50,
    },
    itemNick: {
      fontSize: 32,
      color: "#8a5839",
      verticalAlign: "middle",
      width: 270,
      height: 37,
      textStrokeColor: "#373899",
      textStrokeWidth: 1,
      marginLeft: 24,
    },
    itemBtn: {
      position: "absolute",
      left: 502,
      top: 66,
      width: 161,
      height: 64,
    },
    itemBtnText: {
      fontSize: 32,
      color: "#f8fde4",
      verticalAlign: "middle",
      width: 161,
      height: 64,
      textAlign: "center",
      textStrokeWidth: 4,
      textStrokeColor: "#4d7b26",
      position: "absolute",
      left: 0,
      top: 0,
      lineHeight: 64,
    },
  };

  try {
    console.log("[OpenData][createStyle]", JSON.stringify({
      input: {
        viewPort: viewPort,
        canvasHeight: canvasHeight,
      },
      output: {
        container: style.container,
        list: style.list,
        emptyText: style.emptyText,
        item: style.item,
        itemBtn: style.itemBtn,
      }
    }));
  } catch (err) {
    console.log("[OpenData][createStyle]", style);
  }

  return style;
};
// @prefab-sync-end