// @prefab-sync-start - auto generated by sync-prefab-layout.js
// template from prefab/UISocialInviteView.lh
function escapeAttr(value) {
    return String(value == null ? "" : value)
        .replace(/&/g, "&amp;")
        .replace(/"/g, "&quot;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
}

function tplFunc(it) {
    var data = it && it.data ? it.data : [];
    var out = '<view id="container">';
    if (!data.length) {
        out += '<text id="emptyText" class="emptyText" value="暂无可邀请的微信好友"></text>';
    } else {
        out += '<scrollview id="list" class="list" scrollY="true">';
        for (var i = 0; i < data.length; i++) {
            var item = data[i];
            var avatar = item.avatarUrl ? item.avatarUrl : "openDataContext/image/icon_800000.png";
            out += '<view class="item">';
            out += '<image class="itemBg" src="openDataContext/image/ui_frame_qswj_d.png"></image>';
            out += '<view class="itemRow">';
            out += '<image class="itemHead" src="' + escapeAttr(avatar) + '"></image>';
            out += '<text class="itemNick" value="' + escapeAttr(item.nickName || "玩家昵称") + '"></text>';
            out += '<view class="itemBtnWrap">';
            out += '<image id="btn_' + i + '" class="itemBtn" src="openDataContext/image/ui_btn_ty_g2.png"></image>';
            out += '<text class="itemBtnText" value="邀请"></text>';
            out += "</view></view></view>";
        }
        out += "</scrollview>";
    }
    out += "</view>";
    return out;
}

module.exports = tplFunc;
// @prefab-sync-end
