// @prefab-sync-start - auto generated by sync-prefab-layout.js
// image paths from prefab/UISocialInviteView.lh
export const OPEN_DATA_IMAGES = {
    itemBg: "image/ui_frame_qswj_d.png",
    inviteBtn: "image/ui_btn_ty_g2.png",
    defaultAvatar: "image/icon_800000.png",
} as const;

export const OPEN_DATA_ASSETS = Object.values(OPEN_DATA_IMAGES);
// @prefab-sync-end
