import { OPEN_DATA_IMAGES } from "./OpenDataAssets";
import { InviteUser } from "./types";

// @prefab-sync-start - auto generated by sync-prefab-layout.js
// layout from prefab/UISocialInviteView.lh
const DESIGN_W = 720;
const DESIGN_H = 1280;

// list_items
const LIST = { x: 16, y: 91, width: 696, height: 1047, bottom: 142 };
// item template
const ITEM = { width: 688, height: 200, rowGap: -15 };
const ITEM_STEP = ITEM.height + ITEM.rowGap;

// item children
const ITEM_BG = { y: 28, width: 688, height: 172 };
const ITEM_HEAD = { x: 38, y: 64, size: 100 };
const ITEM_NICK = { x: 162, y: 95, width: 270, height: 37, fontSize: 32, color: "#8a5839", strokeColor: "#373899" };
const ITEM_BTN = { cx: 582, cy: 114, width: 161, height: 64 };
const ITEM_BTN_TEXT = { text: "邀请", fontSize: 32, color: "#f8fde4", stroke: 4, strokeColor: "#4d7b26" };
// @prefab-sync-end

export default class UISocialInviteView extends Laya.Sprite {
    private _listPanel = new Laya.Panel();
    private _emptyLabel = new Laya.Label();
    private _scaleX = 1;
    private _scaleY = 1;
    private _itemWidth = ITEM.width;

    constructor(private _onInvite: (openid: string) => void) {
        super();
        this._listPanel.vScrollBarSkin = "";
        this.addChild(this._listPanel);

        this._emptyLabel.text = "暂无可邀请的微信好友";
        this._emptyLabel.fontSize = 24;
        this._emptyLabel.color = "#999999";
        this._emptyLabel.align = "center";
        this._emptyLabel.valign = "middle";
        this._emptyLabel.visible = false;
        this.addChild(this._emptyLabel);
    }

    public setUsers(users: InviteUser[]): void {
        this.visible = true;
        this.layout();
        this._listPanel.removeChildren();

        const list = users || [];
        this._emptyLabel.visible = list.length === 0;
        this._listPanel.visible = list.length > 0;
        list.forEach((user, index) => {
            this._listPanel.addChild(this.createItem(user, index));
        });
        this._listPanel.refresh();
    }

    public layout(): void {
        const w = this.width;
        const h = this.height;
        this._scaleX = w / DESIGN_W;
        this._scaleY = h / DESIGN_H;
        this._itemWidth = ITEM.width * this._scaleX;

        const listX = LIST.x * this._scaleX;
        const listY = LIST.y * this._scaleY;
        const listW = w - listX * 2;
        const listH = h - listY - LIST.bottom * this._scaleY;

        this._listPanel.pos(listX, listY);
        this._listPanel.size(listW, listH);
        this._emptyLabel.pos(listX, listY);
        this._emptyLabel.size(listW, listH);
    }

    private createItem(user: InviteUser, index: number): Laya.Box {
        const sx = this._scaleX;
        const sy = this._scaleY;
        const itemH = ITEM.height * sy;
        const itemW = this._itemWidth;

        const item = new Laya.Box();
        item.size(itemW, itemH);
        item.y = index * ITEM_STEP * sy;

        const bg = new Laya.Image();
        bg.skin = OPEN_DATA_IMAGES.itemBg;
        bg.pos(0, ITEM_BG.y * sy);
        bg.size(ITEM_BG.width * sx, ITEM_BG.height * sy);
        item.addChild(bg);

        const imgHead = new Laya.Image();
        imgHead.pos(ITEM_HEAD.x * sx, ITEM_HEAD.y * sy);
        imgHead.size(ITEM_HEAD.size * sx, ITEM_HEAD.size * sy);
        imgHead.skin = user.avatarUrl || OPEN_DATA_IMAGES.defaultAvatar;
        item.addChild(imgHead);

        const txtNick = new Laya.Label();
        txtNick.text = user.nickName || "玩家昵称";
        txtNick.fontSize = ITEM_NICK.fontSize * sy;
        txtNick.color = ITEM_NICK.color;
        txtNick.strokeColor = ITEM_NICK.strokeColor;
        txtNick.stroke = 1;
        txtNick.valign = "middle";
        txtNick.pos(ITEM_NICK.x * sx, ITEM_NICK.y * sy);
        txtNick.size(ITEM_NICK.width * sx, ITEM_NICK.height * sy);
        txtNick.overflow = "hidden";
        item.addChild(txtNick);

        const btnW = ITEM_BTN.width * sx;
        const btnH = ITEM_BTN.height * sy;
        const btnX = ITEM_BTN.cx * sx - btnW * 0.5;
        const btnY = ITEM_BTN.cy * sy - btnH * 0.5;

        const btnInvite = new Laya.Image();
        btnInvite.skin = OPEN_DATA_IMAGES.inviteBtn;
        btnInvite.pos(btnX, btnY);
        btnInvite.size(btnW, btnH);
        btnInvite.mouseEnabled = true;
        btnInvite.on(Laya.Event.CLICK, this, () => this._onInvite(user.openid));
        item.addChild(btnInvite);

        const txtTitle = new Laya.Label();
        txtTitle.text = ITEM_BTN_TEXT.text;
        txtTitle.fontSize = ITEM_BTN_TEXT.fontSize * sy;
        txtTitle.color = ITEM_BTN_TEXT.color;
        txtTitle.stroke = ITEM_BTN_TEXT.stroke;
        txtTitle.strokeColor = ITEM_BTN_TEXT.strokeColor;
        txtTitle.align = "center";
        txtTitle.valign = "middle";
        txtTitle.size(btnW, btnH);
        txtTitle.pos(btnX, btnY);
        txtTitle.mouseEnabled = false;
        item.addChild(txtTitle);

        return item;
    }
}
