import Main from "./Main";

/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

/*
* 游戏初始化配置;
*/
export default class GameConfig {
    static width: number = 720;
    static height: number = 1280;
    static scaleMode: string = "fixedwidth";
    static screenMode: string = "vertical";
    static alignV: string = "middle";
    static alignH: string = "center";
    static startScene: any = "Scene.ls";
    static sceneRoot: string = "";
    static debug: boolean = false;
    static stat: boolean = false;
    static physicsDebug: boolean = false;
    static exportSceneToJson: boolean = true;
    constructor() { }
    static init() {
        var reg: Function = Laya.ClassUtils.regClass;
        reg("res://7bad1742-6eed-4d8d-81c0-501dc5bf03d6", Main);
        reg("Main", Main);

    }
}
GameConfig.init();