// auto generated by sync-prefab-layout.js
module.exports = [
    "openDataContext/image/ui_frame_qswj_d.png",
    "openDataContext/image/ui_btn_ty_g2.png",
    "openDataContext/image/icon_800000.png",
];