// @prefab-sync-start - auto generated by sync-prefab-layout.js
// layout from prefab/UISocialInviteView.lh
// nodes resolved by sync-prefab-layout.js
// openData viewport: list@16,0 (prefab list.y=91 为全屏坐标，开放域不重复偏移)
// list: UISocialInviteView/list_items
// item: UISocialInviteView/list_items/item

module.exports = function createStyle(options) {
    options = options || {};

    const viewPort = options.viewPort || null;
    const listHeight =
        viewPort && Number(viewPort.height) > 0
            ? Number(viewPort.height)
            : 1189;

    return {
        container: {
            width: 720,
            height: 1280,
            flexDirection: "column",
        },
        list: {
            width: 696,
            height: listHeight,
            marginLeft: 16,
            marginTop: 0,
            scrollY: true,
            flexDirection: "column",
            alignItems: "center",
        },
        emptyText: {
            width: 696,
            height: 1047,
            marginLeft: 16,
            marginTop: 91,
            fontSize: 24,
            color: "#999999",
            textAlign: "center",
            lineHeight: 1047,
        },
        item: {
            width: 688,
            height: 185,
            position: "relative",
        },
        itemBg: {
            position: "absolute",
            left: 0,
            top: 28,
            width: 688,
            height: 172,
        },
        itemRow: {
            width: 688,
            height: 200,
            flexDirection: "row",
            alignItems: "center",
            paddingLeft: 38,
            paddingRight: 26,
            paddingTop: 64,
            paddingBottom: 21,
        },
        itemHead: {
            width: 100,
            height: 100,
            borderRadius: 50,
        },
        itemNick: {
            fontSize: 32,
            color: "#8a5839",
            verticalAlign: "middle",
            width: 270,
            height: 37,
            textStrokeColor: "#373899",
            textStrokeWidth: 1,
            marginLeft: 24,
        },
        itemBtnWrap: {
            width: 161,
            height: 64,
            marginLeft: 69.5,
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
        },
        itemBtn: {
            width: 161,
            height: 64,
        },
        itemBtnText: {
            fontSize: 32,
            color: "#f8fde4",
            verticalAlign: "middle",
            width: 161,
            height: 64,
            textAlign: "center",
            textStrokeWidth: 4,
            textStrokeColor: "#4d7b26",
            marginTop: -64,
            lineHeight: 64,
        },
    };
};
// @prefab-sync-end