// auto generated by sync-prefab-layout.js
// @prefab-sync-start
module.exports = [
  "openDataContext/image/icon_800000.png",
  "openDataContext/image/ui_btn_ty_g2.png",
  "openDataContext/image/ui_frame_qswj_d.png",
];
// @prefab-sync-end
